### ISSUE TITLE
RscPicture

### ISSUE THREAD

**Issue by xAndreei** [kayler-renslow/arma-dialog-creator#10]
Hey buddy, is it possible to add also the picture dialog?

**Comment by kayler-renslow** [comment]
The picture control is really just the static control with the Picture style setting.

Here are steps:
1. Create static control and remove all styles
2. Select Picture style
3. In the "text" property, you can enter a file path. The path will be relative to the Workspace directory (info [here](https://github.com/kayler-renslow/arma-dialog-creator/wiki/Workspaces-and-Projects)). You can also convert the type of "text" to an Image and then locate the Image file.

You can see an example of RscPicture here: https://community.bistudio.com/wiki/DialogControls-Text#Static_Pictures
