### ISSUE TITLE
Macro color not working for Background color

### ISSUE THREAD

**Issue by tuntematonjr** [kayler-renslow/arma-dialog-creator#14]
### Version and Build
1.0.2

### Summary
When using color macro for  Background color. It give Warning Message: Config : some input after EndOfFile.

### Detail
in export it is writen like this `colorBackground = ORANSSI;`
So it is mising `[]`
it should be `colorBackground[] = ORANSSI;`
Same for 
`colorBackgroundDisabled `and `colorBackgroundActive`

**Comment by kayler-renslow** [comment]
fixed in https://github.com/kayler-renslow/arma-dialog-creator/commit/c8429f908597e27c0eca6bd68cea47dda5f515ba

**Comment by kayler-renslow** [comment]
fix applied in version 1.0.3

**Comment by tuntematonjr** [comment]
@kayler-renslow 
It is doing this still for raw values

**Comment by kayler-renslow** [comment]
fixed https://github.com/kayler-renslow/arma-dialog-creator/commit/25514ca85e139dd1826eb08685bda9599ab4a40a

**Comment by kayler-renslow** [comment]
Fixed in release version 1.0.4
