### ISSUE TITLE
Ää And Öö not supported

### ISSUE THREAD

**Issue by tuntematonjr** [kayler-renslow/arma-dialog-creator#15]
### Version and Build
1.0.2

### Summary
Not sure what is the main problem here, but exported files dont support Ä and Ö in ingame dialog text. 
Edit. These also broke save files

### Detail
I dont know much about this stuff, but i have faced this problem sometimes in arma scripting and i think the problem is in character encoding?
When i convert my hpp file in notepad++ to UTF-8 it fix my problem.

Im from Finland so we have these extra characters. 
Not big thing to convert these files my self but I'd be grateful if you can do something about this =)

**Comment by kayler-renslow** [comment]
Arma 3 only does UTF-8 for localization stuff. As quoted from [here](https://community.bistudio.com/wiki/Stringtable.xml):
> Stringtable.xml must be saved with UTF-8 Encoding for international characters to display and save correctly

It's also generally not a good idea to hard code Strings in your dialog and instead reference them in Stringtable.xml.

I'll look into this issue.

**Comment by tuntematonjr** [comment]
Good to know. Im still trying to learn all this Dialog stuff

**Comment by tuntematonjr** [comment]
Ok so looks like these are breaking save files too.

**Comment by kayler-renslow** [comment]
The encoding issue for XML files has been fixed in https://github.com/kayler-renslow/arma-dialog-creator/commit/1bb311843d4625e9e0c8a6b83bfb687b7a3a5ffd.

**Comment by kayler-renslow** [comment]
fix applied in version 1.0.3
