### ISSUE TITLE
RAW Macro cant create value

### ISSUE THREAD

**Issue by tuntematonjr** [kayler-renslow/arma-dialog-creator#16]
### Version and Build
1.0.2

### Summary
https://i.gyazo.com/9ca5fe2ccc5a2d21ccf01f5d96a53ec1.png
After restarting program. It cant load Raw Macro what i have created.

### Detail
I have made created Raw Macro for getting color from player UI.
`#define UI_OMAVARI {"(profilenamespace getvariable ['GUI_BCG_RGB_R',0.3843])", "(profilenamespace getvariable ['GUI_BCG_RGB_G',0.7019])", "(profilenamespace getvariable ['GUI_BCG_RGB_B',0.8862])", 1}`
https://i.gyazo.com/0e087fb8f3b773e54ac9c4d725288741.png

**Comment by kayler-renslow** [comment]
I'm curious. How did you even assign a color property to a Raw macro? There are barriers in the application to prevent this.

**Comment by kayler-renslow** [comment]
Fixed in commit https://github.com/kayler-renslow/arma-dialog-creator/commit/b6edacee9b3df414bb8d7f7fc474b03389d689dc

**Comment by kayler-renslow** [comment]
fix applied in version 1.0.3
