### ISSUE TITLE
Create new class causes An internal error occurred. Index: 4, Size; 1

### ISSUE THREAD

**Issue by tuntematonjr** [kayler-renslow/arma-dialog-creator#18]
### Version and Build
1.0.2

### Summary
Create new class causes 

> An internal error occurred. Index: 4, Size; 1

### Detail
No idea what is going on. It give same error always when trying to create new class.
Restarting is not helping. Other project work fine. 
https://pastebin.com/Fd0G9Dic
[My project file](https://github.com/kayler-renslow/arma-dialog-creator/files/1275620/Medikaalirasti.zip)

**Comment by kayler-renslow** [comment]
fixed in https://github.com/kayler-renslow/arma-dialog-creator/commit/b8444d2904a8cf563bdfb79661592517e64520e4

**Comment by kayler-renslow** [comment]
fix applied in version 1.0.3
