### ISSUE TITLE
Custom Control Class dont show what it inherit

### ISSUE THREAD

**Issue by tuntematonjr** [kayler-renslow/arma-dialog-creator#23]
### Version and Build
1.0.3. build 24

### Summary
Custom Control Class dont show what it inherit after closing and opening again

### Detail
Create new custom control class.
Try to inherit settings from ohter.
It set that to be inherit from other
Close that class
Open it again and everything you told it to inherit is reset, values are set same as it was suppos to inherit and are changed if changed where it inherite it.

**Comment by tuntematonjr** [comment]
ok tested more and seems it still inherite right value but dont show what it inherit

**Comment by kayler-renslow** [comment]
Well this is a weird bug. This was working fine last version.

**Comment by kayler-renslow** [comment]
This turned out to be a quite systemic bug. How are these not getting caught earlier? lol

**Comment by kayler-renslow** [comment]
fixed in https://github.com/kayler-renslow/arma-dialog-creator/commit/01aa084416d209986411d8c6f50b470e9fcdf282

**Comment by kayler-renslow** [comment]
Fixed in release version 1.0.4
