### ISSUE TITLE
Saving empty project reset custom controll classes file

### ISSUE THREAD

**Issue by tuntematonjr** [kayler-renslow/arma-dialog-creator#25]
### Version and Build
1.0.3. build 24

### Summary
Saving new project overwrites custom control classes file with empty one

### Detail
Saiving just overwrite the old file and old classes are lost.

Restoring backup and reopening that project make them work

**Comment by kayler-renslow** [comment]
fixed in https://github.com/kayler-renslow/arma-dialog-creator/commit/54c8c66a544fd871742fb14303d4c8eba9a9dd0a

**Comment by kayler-renslow** [comment]
Fixed in release version 1.0.4
