### ISSUE TITLE
Missing some User Interface Event Handlers

### ISSUE THREAD

**Issue by tuntematonjr** [kayler-renslow/arma-dialog-creator#27]
### Version and Build
1.0.3. build 24

### Summary
Missing some User Interface Event Handlers
https://community.bistudio.com/wiki/User_Interface_Event_Handlers

### Detail
i need to use onLoad and onDestroy events to run script when dialog is opened and closed.

**Comment by kayler-renslow** [comment]
onDestroy is already present. However, onLoad is missing for controls.

**Comment by kayler-renslow** [comment]
Fixed in https://github.com/kayler-renslow/arma-dialog-creator/commit/f958c4eeca697f7cac2cb17956a6d7dd44936b08.

Also fully updated the events to latest wiki revision (18:44, 22 July 2017)

**Comment by kayler-renslow** [comment]
Fixed in release version 1.0.4
