### ISSUE TITLE
Issue when trying to add property to display properties

### ISSUE THREAD

**Issue by NiiRoZz** [kayler-renslow/arma-dialog-creator#3]
Hello,

I tried your application, I found an error:

When you [add a property](https://i.gyazo.com/5cbaadb5382a64a6c07ea498f9b8d3c3.png), an [error message appears](https://i.gyazo.com/de2c2d26e2baf6ec65655925218386de.png)
[Logs](https://hastebin.com/celifasuyo.cs)

After I receive this error, if I close the window, and I click on export in file, this error reappears.

**Comment by kayler-renslow** [comment]
fixed in commit https://github.com/kayler-renslow/arma-dialog-creator/commit/5262d0819982b35016cb8c8a3469a550306740f2 . This fix will be available in next commit.

**Comment by kayler-renslow** [comment]
Not sure why the issue was closed.

**Comment by kayler-renslow** [comment]
Fixed in version 1.0.1
