### ISSUE TITLE
Macro does not supported math operations and manual typing

### ISSUE THREAD

**Issue by DAmNRelentless** [kayler-renslow/arma-dialog-creator#34]
### Version and Build
1.0.5

### Summary
You can only select macros from a dropdown list. If you type it manually, you get an error if you re-open the project.

### Detail
So for testing purposes I created a macro and called it "TEST". It is an int and has the value 1.
After that I created a controlclass with basic values except x, y and w. For x I selected the macro TEST from the macro dropdown list. For y I typed TEST manually. For w I typed TEST * 2 manually.
When I created an element with this as the parent class, everything works as it should and it gets displayed in the editor's preview. But when saving the project and re-opening it, I get these Errors:
"Erros occuring while parsing. Error: Couldn't create value for Control1765...:y. Value [Test ] Recovered: No"
"Erros occuring while parsing. Error: Couldn't create value for Control1765...:w. Value [Test ] Recovered: No"
When I check my control class the values for y and w are empty now, only x is still present because I used the dropdown list there.

Would be really cool if you implement that you can type in your macro manually and use it with math operations as it should work.

**Comment by Thonikum** [comment]
The same happened to me as well.

**Comment by kayler-renslow** [comment]
Macros are allowed to be typed in manually, but it appears you have found a bug with the project loading. I'll take a look into this.

**Comment by kayler-renslow** [comment]
Fixed in https://github.com/kayler-renslow/arma-dialog-creator/commit/5fe9237b60e8fde1f606aa126253007682795cb0

**Comment by kayler-renslow** [comment]
fixed in release 1.0.6
