### ISSUE TITLE
Save Export Settings

### ISSUE THREAD

**Issue by xetra11** [kayler-renslow/arma-dialog-creator#43]
I'd like to be able to save my export settings because I always have to reenter export location and filename

**Comment by StickieBE** [comment]
@xetra11 This is already an existing ADC feature as you can see below.
![afbeelding](https://user-images.githubusercontent.com/15276515/54788134-4f0d7780-4c2e-11e9-9055-25d2a5f9cc89.png)
I was unable to quickly locate it in the wiki though so opted to paste you a screenshot.

KR
