### ISSUE TITLE
*.paa is not displayed even though Arma Tools directory is set

### ISSUE THREAD

**Issue by xetra11** [kayler-renslow/arma-dialog-creator#44]
### Version and Build
v1.0.7

### Summary
I have a *.paa image which does already work inside ArmA3. I now want to use it in the ADC Preview so I can adjust the control to this image.

### Detail
C:\Users\xetra11\Documents\Arma Dialog Creator\image.paa
C:\Users\xetra11\Documents\Arma Dialog Creator\CoopR Recon Report\image.paa (the project directory)

The config of my background control:

```class ControlsBackground
	{
		class CoopR_ReconReport_Background
		{
			type = 0;
			idc = 11050;
			x = safeZoneX + safeZoneW * 0.26875;
			y = safeZoneY + safeZoneH * 0.12666667;
			w = safeZoneW * 0.4625;
			h = safeZoneH * 0.75;
			style = 2;
			text = "image.paa";
			colorBackground[] = {0.8549,0.8902,0.5373,1};
			colorText[] = {0.7412,0.4706,0.7922,1};
			font = "PuristaMedium";
			sizeEx = (((((safezoneW / safezoneH) min 1.2) / 1.2) / 25) * 1);
			
		};
		
	};
```

Result: https://imgur.com/a/OmHnhys

**Comment by kayler-renslow** [comment]
You don't have the Picture style set. `style` should be set to 48 (Picture) not 2 (Center)

**Comment by kayler-renslow** [comment]
https://community.bistudio.com/wiki/Dialog_Control#CONTROL_STYLES

**Comment by xetra11** [comment]
Thanks dude! Legend
I love your tool!
