### ISSUE TITLE
Rotation of Controls

### ISSUE THREAD

**Issue by xetra11** [kayler-renslow/arma-dialog-creator#45]
Is it possible to rotate controls somehow? I only could scale them atm.

**Comment by kayler-renslow** [comment]
Arma 3 doesn't support rotating controls as far as I'm aware. ADC doesn't support it either.

**Comment by xetra11** [comment]
https://community.bistudio.com/wiki/ctrlSetAngle
This kinda let me thing it is possible?

**Comment by kayler-renslow** [comment]
I wasn't aware of this. Although, the documentation of the command states it applies to the picture itself and not the control. It's also an SQF command, not a static attribute like `x` or `colorText`, so I don't see how ADC could apply this.

**Comment by xetra11** [comment]
Okay sad but true 💃 
thx!
