### ISSUE TITLE
Issue when creating custom control class.

### ISSUE THREAD

**Issue by StickieBE** [kayler-renslow/arma-dialog-creator#5]
Error popped up after editing the attributes class for custom StructuredText class.
(It also seems to be stuck in a loop after I wrongfully assigned a parent class to the attribute and crashed few attempts to save later.)

Screenshot:
http://prntscr.com/g8y54k

LOG:
https://pastebin.com/hUBWKmms

**Comment by kayler-renslow** [comment]
fixed in https://github.com/kayler-renslow/arma-dialog-creator/commit/fb23fc5d25504cc5d89ee33d4611446e856cb4a2

**Comment by kayler-renslow** [comment]
fixed in release 1.0.2
