### ISSUE TITLE
Importing description.ext fails when adding comments after an include.

### ISSUE THREAD

**Issue by StickieBE** [kayler-renslow/arma-dialog-creator#6]
Workaround is to just remove the comments in description.ext.

Screenshot:
http://prntscr.com/g8ydhe

LOG:
https://pastebin.com/DmathjCs

**Comment by kayler-renslow** [comment]
Can you post your description.ext file line 774 please? I would like to see how you wrote the comment because comments are supported in import.

**Comment by StickieBE** [comment]
@kayler-renslow made sure to include it in the screenshot. It contains another "/" in the comment, my guess is it's that.
Screenshot shows a breakpoint and selected line.

**Comment by kayler-renslow** [comment]
Thanks for this. I'll investigate.

**Comment by kayler-renslow** [comment]
fixed in https://github.com/kayler-renslow/arma-dialog-creator/commit/404204feaf30947b335bd2d37f7def6084ea2bad

**Comment by kayler-renslow** [comment]
fixed in release 1.0.2
