### ISSUE TITLE
Issue when importing dialogs.

### ISSUE THREAD

**Issue by StickieBE** [kayler-renslow/arma-dialog-creator#7]
Workaround is to add an empty control class.
```sqf
class controls {
		
};
```

Screenshot:
https://prnt.sc/g8yhiu
Log:
https://pastebin.com/RKGNGm3z

**Comment by kayler-renslow** [comment]
fixed in https://github.com/kayler-renslow/arma-dialog-creator/commit/21d4f993b5768ddc0b897e4721f6743fa33a3f55

**Comment by kayler-renslow** [comment]
fixed in release 1.0.2
